### ISSUE TITLE
Unable to register multiple Routes.

### ISSUE THREAD

**Issue by plugowski** [chinleung/laravel-multilingual-routes#20]
Hi I'm unable to register multiple routes. When I put that into web.php

```php

Route::multilingual('/', function () {
    return view('layout');
})->name('home');

Route::multilingual('/products', 'ProductsController@show');
```

First url works with multiple languages, but when I type `/products` or `/th/products` I receive 404 all the time. When I changed second entry into `::get` it works...

**Comment by chinleung** [comment]
Hi @plugowski,

You can see the registered routes with `php artisan route:list` to see the outcome. However, I can see a few issues here. You are registering with `/products`, therefore the route will be translated to `routes./products`.

Instead, you could change it for:

```php
Route::multilingual('products', 'ProductsController@show');
```

And if you need to translate the products for your other locales, simply create a `routes.php` in the locale's lang folder and add the following:

```php
return [
    'products' => 'produits',
];
```

**Comment by plugowski** [comment]
Hi,

I listed routes and I tried both ways `/products`, as well as `products`, both shows me the 404 page. That what I get by route:list:

`|        | GET|HEAD | routes.products    | en.products | App\Http\Controllers\ProductsController@show | web          |
|        | GET|HEAD | th/routes.products | th.products | App\Http\Controllers\ProductsController@show | web          |`

If I change:
`Route::multilingual('products', 'ProductsController@show');`

to the:
`Route::get('products', 'ProductsController@show');`

website works fine, so find my controller and action, what is strange everything works for main page `/` I see different locales...

**Comment by chinleung** [comment]
@plugowski You need to add your translation files. Please make sure you have a `resources/lang/en/routes.php` and a `resources/lang/th/routes.php` with the `products` as a translation.

For instance:

```php
// resources/lang/en/routes.php

return [
    'products' => 'products',
];
```

**Comment by plugowski** [comment]
Whoa, it works :P I think that information about routes.php file should be better pointed in README ;) Thanks a lot!
