### ISSUE TITLE
Add a localized and multilingual version of Request::routeIs()

### ISSUE THREAD

**Issue by Firer** [chinleung/laravel-multilingual-routes#22]
In views, `Request::routeIs()` very useful for conditional matching of the current route. For instance when adding a class for a current active navigation link:
`{!! Request::routeIs('home.index') ? ' class="active"' : '' !!}`

This works nicely under a regular `GET` route like:
`Route::GET('/', 'HomeController@index')->name('home.index');`

However when we make the route multilingual:
`Route::multilingual('/', 'HomeController@index')->name('home.index');`

It no longer works so nicely, and now we need to handle it with something like:
`{!! Request::routeIs(App::getLocale() . '.home.index') ? ' class="active"' : '' !!}`

Maybe a new method could be a useful enhancement here to help with matching these multilingual routes. Perhaps something along the lines of `Request::localizedRouteIs('home.index')` or `Request::multilingualRouteIs('home.index')`? Or maybe something as simple as a new helper function such as `localized_route_is('home.index')`?

Thanks!

**Comment by chinleung** [comment]
@Firer Sounds good! I'm going to work on it either this or next weekend! You could submit a PR if you'd like to as well! 😄

**Comment by chinleung** [comment]
@Firer I've added `Request::localizedRouteIs('home');` which is available as of [v1.5.0](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v1.5.0).
