### ISSUE TITLE
Add localized version of redirect->route()

### ISSUE THREAD

**Issue by Firer** [chinleung/laravel-multilingual-routes#24]
Hey, I have another feature request, sorry for bothering you with them!

Usually when redirecting to a route we do someting like:
`return Redirect::route('home.index');`

but this doesn't work with multilingual routes. Instead, this work-around seems to do the job for now:
`return Redirect::route(App::getLocale() . '.home.index');`

My suggestion would be to add a localized version of this so that we can do something like:
`return Redirect::localized_route('home.index');`, or perhaps some sort of `localized_redirect()` helper function.

**Comment by chinleung** [comment]
@Firer No worries! Good idea, I'll add it in the next version, which will most likely be the upcoming weekend.

**Comment by chinleung** [comment]
@Firer I've added `Redirect::localizedRoute('home')` which will also be available as of [v1.5.0](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v1.5.0)
