### ISSUE TITLE
Keep both prefixed and not-prefixed route

### ISSUE THREAD

**Issue by yanhao-li** [chinleung/laravel-multilingual-routes#29]
Hi, thank you for making such a clean and easy to use package. 

I have a small question: when I declare my routes like `Route::multilingual('test', 'TestController')->name('foo');` and have 'prefix_default' set to `true`, it will generate following routes:

Method | URI | Name | Action
-- | -- | -- | --
GET\|HEAD | en/test | en.test | App\Http\Controllers\TestController
GET\|HEAD | fr/teste | fr.test | App\Http\Controllers\TestController

Is that possible to simultaneously register the default route?

Method | URI | Name | Action
-- | -- | -- | --
GET\|HEAD | test | test | App\Http\Controllers\TestController

Thank you in advance!

**Comment by chinleung** [comment]
Hi @yanhao-li,

What do you mean by `default route`?

Wouldn't you just achieve the result you want with the regular router?

```php
Route::get('test', 'TestController');
```

**Comment by yanhao-li** [comment]
Method | URI | Name | Action
-- | -- | -- | --
GET\|HEAD | en/test | en.test | App\Http\Controllers\TestController
GET\|HEAD | fr/teste | fr.test | App\Http\Controllers\TestController
GET\|HEAD | test | test | App\Http\Controllers\TestController

Wouldn't that mean in order to get such a result I will have to duplicate my route declaration?

Route::multilingual('test', 'TestController');
Route::get('test', 'TestController');

**Comment by chinleung** [comment]
Oh, I thought you only wanted the `/test` without the two others.

But then what will happen when the user visit `/test` and which locale is that route?

**Comment by yanhao-li** [comment]
I plan to use the fallback locale, or if user has visited the site before, then using the locale stored in cookies, just want to keep the URL clean.

**Comment by chinleung** [comment]
Hmm... But then that would cause duplicated content for your SEO. Shouldn't it redirect to the route of your fallback locale instead? For instance, redirect `/test` to `/en/test`? Or simply not prefix the default locale?

**Comment by yanhao-li** [comment]
Well, SEO might be an issue, but to some extent, the pages of `/en` and `/fr` are also duplicate content, merely in a different language. 

To me, it's just somewhat weird to always have a prefix in the URL, which in most cases that user don't have to care about, especially when you are designing an application that don't require SEO much, for example facebook.com, which will not append the prefix when you change language.

**Comment by chinleung** [comment]
If you are aiming to build something like an application, this package is not really suited because in applications like Facebook, their links are always the same no matter the locale. The locale of the application change based on the user's language preferences instead of the route. In that case, what you should do is add a `locale` property to your `App\User` model and load the locale based on the chosen language.

This package is meant for website that has the locale based on the url.

**Comment by yanhao-li** [comment]
ok, thank you for the replies. Closing this ticket.
