### ISSUE TITLE
composer only install the old version

### ISSUE THREAD

**Issue by naja7host** [chinleung/laravel-multilingual-routes#34]
installing the packages via composer in a laravel 7.0 return installation of v 1.0.0, when we force to install the latest version 2.3.0 compser return the error

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package chinleung/laravel-locales ^2.3.0 exists as chinleung/laravel-locales[dev-master, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.1.0, v1.2.0] but these are rejected by your constraint.

**Comment by chinleung** [comment]
@naja7host Did you figure it out? Asking since you've closed the issue.
