### ISSUE TITLE
Suggestion to add fallback for current_route helper

### ISSUE THREAD

**Issue by jeffreyvr** [chinleung/laravel-multilingual-routes#36]
Thanks for the package, works well!

This is not so much an issue, but more a specific use case I ran into.

Only part of my app uses localized pages. In the footer of my site I have a language switcher dropdown. Within this dropdown I'm using the `current_route` helper.

 Sometimes (it's rare, but it happens) a page is not localized and using the `Route::multilingual()` route registration.

When you then call `current_route`, this will result in a `ViewException`. I added a very simple helper to fallback on the current path of the request when that happens.

I'm not saying that this should be default behavior, since you might also think: why are you showing that dropdown in the first place. I still thought I'd share it.

```php
/**
 * Try to get the current route.
 *
 * @param  string $locale The locale for the current route.
 * @return mixed
 */
function try_current_route($locale = null)
{
    try {
        return current_route($locale);
    } catch(\Exception $e) {
        return request()->path();
    }
}
```

**Comment by chinleung** [comment]
@jeffreyvr The fallback option is now available as of [v1.7.0](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v1.7.0) and [v2.4.0](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v2.4.0). 🎉
