### ISSUE TITLE
Redirections

### ISSUE THREAD

**Issue by chinleung** [chinleung/laravel-multilingual-routes#49]
Add support for multilingual redirections.

```php
Route::multilingual('contact')->redirect('support', 302);
```

To generate the following routes:

```
+------------------+--------------+---------------------------------------+
| URI              | Name         | Action                                |
+------------------+--------------+---------------------------------------+
| contact          | en.contact   | Illuminate\Routing\RedirectController |
| fr/nous-joindre  | fr.contact   | Illuminate\Routing\RedirectController |
+------------------+--------------+---------------------------------------+
```

**Comment by AbdullahFaqeir** [comment]
@chinleung can you please elaborate?

**Comment by chinleung** [comment]
> @chinleung can you please elaborate?

@AbdullahFaqeir 

Basically it will handle the redirections of a route in all locales. As of now, if you want to redirect a route, you'd have to manually add it like this in all locales:

```php
Route::redirect('contact', 'support');
Route::redirect('fr/nous-joindre', 'fr/support');
```

So adding a `redirect` method would handle that.

**Comment by AbdullahFaqeir** [comment]
@chinleung 

This issue to be closed.

**Comment by chinleung** [comment]
This is supported as of [v2.8.0](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v2.8.0).
