### ISSUE TITLE
Another Question - localized_route

### ISSUE THREAD

**Issue by Heqma** [chinleung/laravel-multilingual-routes#52]
Hi, i have another Q becouse i have something like this in href "{{ localized_route('front.index') }}"   with this controller "Route::multilingual('/', 'FrontController@index')->name('front.index');" and it's work..without pl.front.index but why isn't work with other routes like this?

like:
    Route::multilingual('/blog/wpis/{slug}', 'BlogController@show')->name('blog.show');
    href ="{{ localized_route('blog.show') }}"
    
    
 other problem:
 
![image](https://user-images.githubusercontent.com/71975536/120347131-4def2f00-c2fc-11eb-85ae-5b9c6b4e1c6b.png)
![image](https://user-images.githubusercontent.com/71975536/120347164-55aed380-c2fc-11eb-9942-c8e06f6e0967.png)
![image](https://user-images.githubusercontent.com/71975536/120347212-5e9fa500-c2fc-11eb-83d3-d59546c33842.png)

**Comment by chinleung** [comment]
@Heqma You are missing the slug parameter for your route. It should be something like this:

```blade
{{ localized_route('blog.show', ['slug' => $blog->slug]) }}
```

**Comment by Heqma** [comment]
Ok, but it doesnt translate the route and why i need put slug if it is in route?, dont close topics..

**Comment by chinleung** [comment]
> Ok, but it doesnt translate the route and why i need put slug if it is in route?, dont close topics..

Did you add it in your translation files?

```
resources/lang/pl/routes.php
resources/lang/en/routes.php
```

**Comment by Heqma** [comment]
Yes
![image](https://user-images.githubusercontent.com/71975536/120353809-39ae3080-c302-11eb-8793-47a14d1a8b84.png)
![image](https://user-images.githubusercontent.com/71975536/120354427-b4774b80-c302-11eb-9413-7241bd461eb9.png)

![image](https://user-images.githubusercontent.com/71975536/120353946-5a768600-c302-11eb-89ae-71f5bf4e558a.png)
![image](https://user-images.githubusercontent.com/71975536/120354088-7843eb00-c302-11eb-8a02-090a1b8f9f0e.png) - default

**Comment by chinleung** [comment]
@Heqma You only translated the `blog` route. There should be another one:

```php
'blog/wpis/{slug}' => '...',
```

Or you can use a friendly key:

```php
Route::multilingual('show-blog', ...)->name('blog.show');
```

And then add the following in your `routes.php`:

```php
'show-blog' => 'blog/wpis/{slug}',
```

**Comment by Heqma** [comment]
Oh.. i see.. that how it's works..

**Comment by chinleung** [comment]
@Heqma Does it work for you now?
