### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting!

### ISSUE THREAD

**Issue by hinink** [chinleung/laravel-multilingual-routes#58]
Maximum function nesting level of '256' reached, aborting!

**Comment by chinleung** [comment]
@zc520yzy Do you have any code to reproduce?

**Comment by AbdullahFaqeir** [comment]
This exception is caused by a recursive call that keeps going as the stop condition isn't reached, it's an error thrown mostly from xdebug, could you please provide a code sample from where this issue is happening?
