### ISSUE TITLE
Binding routes not working

### ISSUE THREAD

**Issue by ricardogobbosouza** [chinleung/laravel-multilingual-routes#61]
Binding routes not working

```php
Route::multilingual('test/{test:slug}', 'TestController');
```

On reset uri https://github.com/chinleung/laravel-multilingual-routes/blob/v2/src/MultilingualRegistrar.php#L301 the `bindingFields` are cleared.

**Comment by chinleung** [comment]
This is fixed as of [v2.8.1](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v2.8.1).
