### ISSUE TITLE
InvalidArgumentException Attribute [multilingual] does not exist.

### ISSUE THREAD

**Issue by MatejMozola** [chinleung/laravel-multilingual-routes#65]
Hi, just uploaded on server, worked fine on local environment. Can anyone guess what might be the problem?

**Comment by chinleung** [comment]
> Hi, just uploaded on server, worked fine on local environment. Can anyone guess what might be the problem?

Hey @MatejMozola,

It's hard to help without more information. The method is added via the service provider `MultilingualRoutesServiceProvider.php`.

Is the service provider loaded on your server?

**Comment by MatejMozola** [comment]
Finally solved the problem, yes I uploaded all new or edited files but problem was I didnt upload /bootstrap/cache/routes-v7.php file. Thank you for a great package and keep up the good work.
