### ISSUE TITLE
Cannot be used with Laravel 11

### ISSUE THREAD

**Issue by da40** [chinleung/laravel-multilingual-routes#83]
**Describe the bug**

laravel-multilingual-routes 4.1 is dependent on "illuminate/support" which has been replaced by "laravel/framework" in Laravel 11.

**To Reproduce**

1. Change "laravel/framework" in composer.json to "^11.0".
2. composer update

**Expected behavior**

All dependencies to be resolved.

**Result of route:list**:

N/A

**Additional context**

I previously erroneously reported that the issue was only with laravel-locales.

**Comment by chinleung** [comment]
Hey @da40,

I just tried to install it and it works properly in a fresh Laravel 11 install with the [v2.1.0 release of laravel-locales](https://github.com/chinleung/laravel-locales/releases/tag/v2.1.0).

Output of `php artisan --version`:
<img width="340" alt="image" src="https://github.com/chinleung/laravel-multilingual-routes/assets/19669331/865a2f24-707f-4e31-af94-0fe5abbfabeb">

Output of `composer require chinleung/laravel-multilingual-routes`:
<img width="984" alt="image" src="https://github.com/chinleung/laravel-multilingual-routes/assets/19669331/bbcc9dc4-9a80-4b92-a108-02273419c4f7">

Feel free to re-open the issue if you are still facing the issue.
