### ISSUE TITLE
Undefined uri for home route

### ISSUE THREAD

**Issue by esadewater** [chinleung/laravel-multilingual-routes#84]
**Describe the bug**

Registering a route for the `/` path will result in an empty uri for the default locale.

**To Reproduce**

Steps to reproduce the behaviour:

Register a route for the `/` path:
```
Route::multilingual('/', [HomeController::class, 'index'])->name('home')
```

While also having a default locale set:
```
return [
    'default' => 'de'
]
```

**Result of route:list**:

```
 GET|HEAD    ....................................................... de.index › HomeController@index
 GET|HEAD   en ..................................................... en.index › HomeController@index
```

**Expected behavior**

I would expect that the home route for the default locale would be registered for the `/`uri instead of an empty uri.

**Additional context**

Using the home route with together with [tighten/ziggy](https://github.com/tighten/ziggy) will result in an undefined uri, e.g. `route('de.home')` would output `undefined` and therefore making it unusable.

**Comment by esadewater** [comment]
I did some research in the `MultilingualRegistrar` and found that the empty uri is produced in the `finalizeRoute` function. After cleaning up the unique registration keys, we prefix all but the default locale and therefore ending with an empty uri. We could add a special case after adding the locale prefixes [here](https://github.com/chinleung/laravel-multilingual-routes/blob/d1e2455baf4506c729fe453454049e41672cd377/src/MultilingualRegistrar.php#L199) that replaces the empty uri with a `/`

**Comment by chinleung** [comment]
Hey @esadewater, this has been fixed in https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v4.1.2.
