### ISSUE TITLE
Prefixes in wrong order when Route::prefix groups

### ISSUE THREAD

**Issue by ef2-delanoderooij** [chinleung/laravel-multilingual-routes#9]
When using route groups that have a prefix defined will have the prefixes set in the wrong order.

```php 
Route::prefix('backend')->group(function () {
    Route::multilingual('/users', 'UsersController@index')->name('backend.users.index');
});
```

Expected Output | Actual Output
------------ | -------------
en/backend/users | backend/en/users

**Comment by chinleung** [comment]
@ef2-delanoderooij Nice catch. This is fixed in [v1.2.2](https://github.com/chinleung/laravel-multilingual-routes/releases/tag/v1.2.2).
